/*	opendatacon
 *
 *	Copyright (c) 2014:
 *
 *		DCrip3fJguWgVCLrZFfA7sIGgvx1Ou3fHfCxnrz4svAi
 *		yxeOtDhDCXf1Z4ApgXvX5ahqQmzRfJ2DoX8S05SqHA==
 *
 *	Licensed under the Apache License, Version 2.0 (the "License");
 *	you may not use this file except in compliance with the License.
 *	You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 *	Unless required by applicable law or agreed to in writing, software
 *	distributed under the License is distributed on an "AS IS" BASIS,
 *	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *	See the License for the specific language governing permissions and
 *	limitations under the License.
 */
/*
 * api_shim.c
 *
 *  Created on: 09/06/2026
 *      Author: Neil Stephens <dearknarl@gmail.com>
 */

#include "opendatacon/odc_c_api.h"

/* On Windows, plain C symbols in a Go c-shared DLL are not exported
 * automatically — only Go //export functions get __declspec(dllexport).
 * Mark every public entry point explicitly so GetProcAddress can find them. */
#ifdef _WIN32
#  define ODC_C_EXPORT __declspec(dllexport)
#else
#  define ODC_C_EXPORT
#endif

/* Host API vtable — set by odc_library_init() before any port is created.
   All port-side calls to host services go through this pointer. */
struct C_ODC_HostAPI* odc = NULL;

/* ------------------------------------------------------------------ */
/*  Go-exported internal functions (generated by cgo in _cgo_export.c) */
/* ------------------------------------------------------------------ */
extern void* go_port_create(char* type, char* name);
extern void  go_port_destroy(void* inst);
extern void  go_port_build(void* inst);
extern void  go_port_enable(void* inst);
extern void  go_port_disable(void* inst);
extern void  go_port_event(void* inst,
	struct C_EventInfo* event,
	char* sender,
	C_StatusCallback* cb);
extern char* go_port_stats_json(void* inst);
extern char* go_port_state_json(void* inst);
extern char* go_port_status_json(void* inst);
extern void  go_port_free_string(char* str);

/* Go-exported ODC timer callback functions */
extern void go_reconnect_timer_cb(uint8_t status, void* handle);
extern void go_connect_ok_cb(uint8_t status, void* handle);
extern void go_connect_fail_cb(uint8_t status, void* handle);
extern void go_transport_disconnect_cb(uint8_t status, void* handle);

/* ------------------------------------------------------------------ */
/*  C API — const-correct wrappers matching odc_c_api.h exactly        */
/* ------------------------------------------------------------------ */

ODC_C_EXPORT void* odc_port_create(const char* type, const char* name)
{
	return go_port_create((char*)type, (char*)name);
}

ODC_C_EXPORT void odc_port_destroy(void* inst)
{
	go_port_destroy(inst);
}

ODC_C_EXPORT void odc_port_build(void* inst)
{
	go_port_build(inst);
}

ODC_C_EXPORT void odc_port_enable(void* inst)
{
	go_port_enable(inst);
}

ODC_C_EXPORT void odc_port_disable(void* inst)
{
	go_port_disable(inst);
}

ODC_C_EXPORT void odc_port_event(void* inst,
	const struct C_EventInfo* event,
	const char* sender,
	C_StatusCallback* cb)
{
	go_port_event(inst, (struct C_EventInfo*)event, (char*)sender, cb);
}

ODC_C_EXPORT const char* odc_port_stats_json(void* inst)
{
	return go_port_stats_json(inst);
}

ODC_C_EXPORT const char* odc_port_state_json(void* inst)
{
	return go_port_state_json(inst);
}

ODC_C_EXPORT const char* odc_port_status_json(void* inst)
{
	return go_port_status_json(inst);
}

ODC_C_EXPORT const char* odc_c_api_version(void)
{
	return ODC_C_API_VERSION;
}

ODC_C_EXPORT void odc_port_free_string(const char* str)
{
	go_port_free_string((char*)str);
}

/* ------------------------------------------------------------------ */
/*  ODC scheduling helpers — called from Go via cgo.                   */
/*  These translate to odc->ms_timer_callback() calls using the        */
/*  Go-exported callback function pointers above.                      */
/* ------------------------------------------------------------------ */

/* Schedule a reconnect attempt after 'ms' milliseconds.
   Returns the ODC timer handle (pass to odc_cancel_timer to cancel). */
void* odc_schedule_reconnect(void* inst, uint64_t ms)
{
	if (odc && odc->ms_timer_callback)
		return odc->ms_timer_callback(inst, ms, go_reconnect_timer_cb, inst);
	return NULL;
}

/* Signal a connect result back to the strand.  ok != 0 → success. */
void odc_schedule_connect_result(void* inst, int ok)
{
	if (odc && odc->ms_timer_callback)
		odc->ms_timer_callback(inst, 0,
			ok ? go_connect_ok_cb : go_connect_fail_cb, inst);
}

/* Signal a transport disconnect back to the strand from a poll goroutine. */
void odc_schedule_transport_disconnect(void* inst)
{
	if (odc && odc->ms_timer_callback)
		odc->ms_timer_callback(inst, 0, go_transport_disconnect_cb, inst);
}
